version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 20
  target-branch: master
  ignore:
    - dependency-name: "org.apache.maven:maven-plugin-api"
    - dependency-name: "org.antipathy:*"


