name: Build211

on:
  push:
    branches:
      - master

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn clean test scoverage:report -Dversion.scala.major=2.12 -Dversion.scala.minor=.10
      - name: upload coverage_data
        run: wget -qO - https://coverage.codacy.com/get.sh | bash
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  release_2_11:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
          maven_args: -Dversion.scala.major=2.11 -Dversion.scala.minor=.12 -Drevision=$(git show -s --format=%ct.%h)
      - name: tag repo
        uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          name: 'Ciaran Kearney'
          email: 'ciaran@antipathy.org'
          actor: 'SimonJPegg'
          token: '${{ secrets.GITHUB_TOKEN }}'
      - run: bash create_release.sh 2.11 .8 SimonJPegg/mvn_scalafmt "$GITHUB_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
